# config/_default/menus.yaml

main:
  - name: 首页
    url: /
    weight: 10
  - name: 博客
    url: /blog/
    weight: 20
  - name: 标签
    url: /tags/
    weight: 30
  - name: 关于我
    url: /about/
    weight: 40